-- Data.lua
local addonName, addonTable = ...

-- Official set of eating lines
addonTable.OfficialLines = {
    { text = "TURTLE FACTS: these turtles won't make it to the water", weight = 10 },
    { text = "Thanks Ferfeast!", weight = 10 },
    { text = "delicious bread", weight = 10 },
    { text = "Next time... on Saint TV...", weight = 10 },
    { text = "imagine if we wiped?", weight = 10 },
    { text = "is this one of the bosses we pull until it dies?", weight = 10 },
    { text = "what happened to dessia's health?", weight = 10 },
    { text = "FERFIND > UMBRAE", weight = 10 },
    { text = "Praise be to Ferfeast!", weight = 10 },
    { text = "If umbrae eats a fish feast, is it cannibalism?", weight = 10 },
    { text = "While we eat this, let's explain the fight to the newest healer", weight = 10 },
    { text = "Zan, check your talents", weight = 10 },
    { text = "Is Zach online?", weight = 10 },
    { text = "ALL HAIL FERFEAST", weight = 10 },
    { text = "This is my first mehlay character", weight = 10 },
    { text = "Its been a while since we seen a BOE", weight = 10 },
    { text = "The devs must have increased the BOE drop rate, huh?", weight = 10 },
    { text = "Who took Lumbering Form?", weight = 10 },
    { text = "Just be a warrior and BLAST!", weight = 10 },
    { text = "Peanut butter and Mint is the best combination", weight = 10 },
    { text = "We have been raiding together since Cata, remember?", weight = 10 },
    { text = "I don't have money for repairs", weight = 10 },
    { text = "Have you tried Googling, 'LONG FURBY'?", weight = 10 },
    { text = "I need to do this on my hunter", weight = 10 },
    { text = "Have you seen The Jailer's nipples?", weight = 10 },
    { text = "Hold on, I have to open my spellbook for that.", weight = 10 },
    { text = "/ t a r / c a s t spacebar r e b i r t h", weight = 10 },
    { text = "I have every cloak in the game... most of them...", weight = 10 },
    { text = "Why isn't Matt stellspealing?", weight = 10 },
    { text = "I cry at the end of Lord of the Rings: Return of the King everytime I watch it", weight = 10 },
    { text = "Someone remind Splic not to Bone Spike mind controlled people.", weight = 10 },
    { text = "Mom told us to use our eyeballs.", weight = 10 },
    { text = "Ghost Moose Aesthetic sounds like a Canadian Blues-Folk cover band.", weight = 10 },
    { text = "Have you seen a cat backing up? Don't do that.", weight = 10 },
    { text = "I was too busy dying to the Fire Giant", weight = 10 },
    { text = "Everybody kill Merciless", weight = 10 },
    { text = "Everyone stack on STAR", weight = 10 },
    { text = "I think we need to focus more on the quasars", weight = 10 },
    { text = "Literally the second... literally", weight = 10 },
    { text = "I'm having aethernet problems...", weight = 10 },
    { text = "Could someone hold this water so I can make inventory space?", weight = 10 },
    { text = "Oops, I forgot Slappy Hands", weight = 10 },
    { text = "Trust me, I'm a professor of WoW Physics", weight = 10 },
    { text = "This has got to be the hardest boss ever, huh?", weight = 10 },
    { text = "Remember when Survival was bad?", weight = 10 },
    { text = "I need to use the zug jug...", weight = 10 },
    { text = "Reminder: MD/Tricks Saint", weight = 10 },
    { text = "You are not just a pug, but a pug with benefits.", weight = 10 },
    { text = "That was my first BOE this expansion", weight = 10 },
    { text = "Someone drop Meerah's Jukebox for a sing-a-long", weight = 10 },
    { text = "Sorry, I was doing dishes... and homework", weight = 10 },
    { text = "Having performance issues... running out of vigor.", weight = 10 },
    { text = "Does cleaving count as target switching?", weight = 10 },
    { text = "I think they put all the difficulty on this boss", weight = 10 },
    { text = "I didn't talent into teamwork", weight = 10 },
    { text = "Deepfried Microphone!", weight = 10 },
    { text = "Please wipe, Umbrae...", weight = 10 },
    { text = "Oh, I have Heroic Leap...", weight = 10 },
    { text = "This f**ker's on farm!!!", weight = 10 },
    { text = "It's Voking Time!", weight = 10 },
    { text = "Wtf is peggle?", weight = 10 },
    { text = "I'm saving the Weak or...", weight = 10 },
    { text = "https://www.twitch.tv/nalhan Hottest thing on Twitch since sliced bread", weight = 10 },
    { text = "Healer?", weight = 10 },
    { text = "Jeremy Wisecarver", weight = 10 },
    { text = "The patch comes out next week, yeah?", weight = 10 },
    { text = "Anyone up for a quick AV?", weight = 10 },
    { text = "Did someone mention steak?", weight = 10 },
    { text = "There is the oiliest duck, returning from a shower.", weight = 10 },
    { text = "Quick, in and out.", weight = 10 },
    { text = "Which one is Darryl?", weight = 10 },
    { text = "I'm Darryl!", weight = 10 },
    { text = "Have you been to Stonard recently?", weight = 10 },
    { text = "I can't laugh too hard, my headset will fall off.", weight = 10 },
    { text = "No worries, I got you in 8 minutes.", weight = 10 },
    { text = "We are number #1 and #2 on the Arthas.", weight = 10 },
    { text = "My number small on lumberjack website", weight = 10 },
    { text = "Who pulled?", weight = 10 },
    { text = "Narc!", weight = 10 },
    { text = "One of the bosses of all time...", weight = 10 },
    { text = "BOP me! BOP me!", weight = 10 },
    { text = "I don't have enough talent points for that.", weight = 10 },
    { text = "Bacon is off cooldown!", weight = 10 },
    { text = "I just finished the first season of Umbrella Factory!", weight = 10 },
    { text = "I really need the Advil to drop...", weight = 10 },
    { text = "Buff shadow priest?", weight = 10 },
    { text = "I'm getting peanut butter & jelly delivered, and it's taking forever...", weight = 10 },
    { text = "Yellow is not Red.", weight = 10 },
    { text = "I made him a Sporecloak, so he should be good, right?", weight = 10 },
    { text = "Zan's glitching...", weight = 10 },
    { text = "Imagine taking damage...", weight = 10 },
    { text = "Ooo, that prosecco coming!", weight = 10 },
    { text = "he need revive.", weight = 10 },
    { text = "Is now a bad time to admit, I've been doing my rotation wrong?", weight = 10 },
    { text = "Have I been muted thus whole time?", weight = 10 },
    { text = "Saint's in HR, so he knows...", weight = 10 },
    { text = "150yrs is the breakpoint to be considered archaeology.", weight = 10 },
    { text = "Have you seen my mog?", weight = 10 },
    { text = "I Saint it with my own two eyes.", weight = 10 },
    { text = "Isn't Jarrito, Naruto's brother?", weight = 10 },
    { text = "Didn't you listen to the 100 questions from Quiznos?", weight = 10 },
    { text = "Don't drop a feast when Ray is ressing!", weight = 10 },
    { text = "Quack!", weight = 10 },
    { text = "Is there a wet add and a Dryad?", weight = 10 },
    { text = "It's not Comic Zans, its Happy Giraffe!", weight = 10 },
    { text = "Can I get a hunter closet?", weight = 10 },
    { text = "Gamon Pull!!!", weight = 10 },
    { text = "Umbrae, you fix those lights yet?", weight = 10 },
    { text = "God dammit I dropped my jelly!", weight = 10 },
    { text = "Quick, someone quote a Saintism.", weight = 10 },
    { text = "All mail, ew...", weight = 10 },
    { text = "Gloinn can you link the WeakAura?", weight = 10 },
    { text = "Dispell, dispell, dispell, dispell, dispell...", weight = 10 },
    { text = "Manastorm pull?", weight = 10 },
    { text = "I had such a good opener too...", weight = 10 },
    { text = "Don't make me duck terrorist attack you!", weight = 10 },
    { text = "Uh, we are going to get Celethe fired...", weight = 10 },
    { text = "Why can't find the quest?", weight = 10 },
    { text = "Is this only Early Access?", weight = 10 },
    { text = "I need a second weapon for my Bear Spec!", weight = 10 },
    { text = "What group am I in?", weight = 10 },
    { text = "Stay out of the nommie circle!", weight = 10 },
    { text = "Its only pad when we didn't need it.", weight = 10 },
    { text = "Rat Pisscuit!", weight = 10 },
    { text = "Don't gaslight me...", weight = 10 },
    { text = "Since Canadian 9/11, times are tough...", weight = 10 },
    { text = "Put your left hand up, and curl your arm, clockwise...", weight = 10 },
    { text = "You were under my Weakaura...", weight = 10 },
    { text = "It's the legendary 4p Fire Mage!", weight = 10 },
    { text = "That's crazy comms!", weight = 10 },
    { text = "That's BANNED!", weight = 10 },
    { text = "X goes to Diamond", weight = 10 },
    { text = "DPS?", weight = 10 },
    { text = "Tank?", weight = 10 },
    { text = "Jesus Christ Zach takes a lot of damage!", weight = 10 },
    { text = "Get this boss off my screen!", weight = 10 },
    { text = "Oh, it's Blue Prince!", weight = 10 },
    { text = "No worries, Matt and I got that part.", weight = 10 },
    { text = "#FREETHEFEET", weight = 10 },
    { text = "Eat Shit DRAGON!", weight = 10 },
    { text = "I'm slightly more meta then Zeps", weight = 10 },
    { text = "Whenever I gamba, I either win or lose.", weight = 10 },
    { text = "Well... no one gives a shit...", weight = 10 },
    { text = "Zeps, LUST!", weight = 10 },
    { text = "I fingered my bink", weight = 10 },
    { text = "Zeps, Time Spiral!", weight = 10 },
    { text = "The whole gallon of milk!", weight = 10 },
    { text = "Test this idiot", weight = 69 },
}
